server:
  port: 8762

eureka:
  instance:
    hostname: eureka-server-1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka-server:8761/eureka/